root = "cmd/focg-content-creator"
tmp_dir = "../tmp"

[build]
cmd = "go build -o ../tmp/main ."
bin = "../tmp/main"
full_bin = "APP_ENV=dev APP_USER=air ../tmp/main"
args_bin = []
include_ext = ["go", "tpl", "tmpl", "html", "js", "css"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
include_dir = []
include_file = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "../tmp/air.log"
poll = false
poll_interval = 500
delay = 0
stop_on_error = true
send_interrupt = false
kill_delay = 500
rerun = false
rerun_delay = 500

[log]
time = false
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = true
proxy_port = 8090
app_port = 8080